# Generated by Django 3.2.9 on 2021-11-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0002_applicantdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantData',
        ),
    ]
