# Generated by Django 3.2.9 on 2021-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_delete_applicantdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='code_t',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
