# Generated by Django 3.2.9 on 2021-12-01 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion1', '0004_ventas_code_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('pais', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'db_table': 'perfil',
                'ordering': ['id'],
            },
        ),
    ]
