# Generated by Django 3.2.9 on 2021-12-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0008_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripccion',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AddField(
            model_name='productos',
            name='detalles',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
