# Generated by Django 3.2.9 on 2021-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0009_auto_20211207_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=20)),
                ('sala', models.ManyToManyField(related_name='followed', to='aplicacion1.usuarioejemplo')),
            ],
        ),
    ]
