# Generated by Django 3.2.9 on 2021-12-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0010_ejemplo_usuarioejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ejemplo',
        ),
        migrations.DeleteModel(
            name='usuarioejemplo',
        ),
    ]
