# Generated by Django 3.2.9 on 2021-12-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0012_article_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
