# Generated by Django 3.2.9 on 2022-01-03 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacion1', '0013_auto_20211230_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas_concertadas', models.IntegerField(default=0)),
                ('acumulado', models.FloatField(default=0.0)),
                ('publications', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
