# Generated by Django 3.2.9 on 2022-01-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0014_historial_ventas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_ventas',
            old_name='publications',
            new_name='usuario',
        ),
    ]
