# Generated by Django 3.2.9 on 2022-01-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0015_rename_publications_historial_ventas_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historial_ventas',
        ),
    ]
