# Generated by Django 3.2.9 on 2022-01-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0016_delete_historial_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
