# Generated by Django 3.2.9 on 2021-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rico', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'ejemplo',
                'verbose_name_plural': 'ejemplos',
                'db_table': 'ejemplo',
                'ordering': ['id'],
            },
        ),
    ]
