# Generated by Django 3.2.9 on 2021-12-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cede_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ejemplo',
        ),
    ]
