# Generated by Django 3.2.9 on 2021-12-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicacion1', '0009_auto_20211207_0400'),
        ('cede_app', '0002_delete_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='estados_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField()),
                ('detalles', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion1.productos')),
            ],
            options={
                'verbose_name': 'estados_producto',
                'verbose_name_plural': 'estados_productos',
                'db_table': 'estados_producto',
                'ordering': ['id'],
            },
        ),
    ]
