# Generated by Django 3.2.9 on 2021-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cede_app', '0004_estados_productos_verficacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estados_productos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='estados_productos',
            name='producto',
        ),
        migrations.AddField(
            model_name='estados_productos',
            name='code_t',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
