# Generated by Django 3.2.9 on 2021-12-11 15:13

import core.cede_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cede_app', '0005_auto_20211211_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados_productos',
            name='img1',
            field=models.ImageField(default='none', upload_to=core.cede_app.models.path_file_name),
            preserve_default=False,
        ),
    ]
