# Generated by Django 3.2.9 on 2021-12-11 15:17

import core.cede_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cede_app', '0006_estados_productos_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados_productos',
            name='img2',
            field=models.ImageField(default='none', upload_to=core.cede_app.models.path_file_name),
        ),
        migrations.AddField(
            model_name='estados_productos',
            name='img3',
            field=models.ImageField(default='none', upload_to=core.cede_app.models.path_file_name),
        ),
        migrations.AddField(
            model_name='estados_productos',
            name='img4',
            field=models.ImageField(default='none', upload_to=core.cede_app.models.path_file_name),
        ),
        migrations.AlterField(
            model_name='estados_productos',
            name='img1',
            field=models.ImageField(default='none', upload_to=core.cede_app.models.path_file_name),
        ),
    ]
